[build-system]
requires = ["setuptools>=45", "setuptools-scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"


[tool.setuptools_scm]
write_to = "src/cvmfs/_version.py"

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64"]

[tool.pixi.dependencies]
python = ">=3.8"
cryptography = "*"
pip = "*"
setuptools-scm = "*"
httpx = "*"
h2 = "*"

[tool.pixi.pypi-dependencies]
cvmfsutils = { path = ".", editable = true }

[tool.pixi.environments]
testing = ["test"]

[tool.pixi.feature.test.dependencies]
unittest-xml-reporting = "*"

[tool.pixi.feature.test.tasks]
test = "python -m cvmfs.test"

[tool.pixi.tasks]
generate-spec = "python generate_spec.py"
